### ISSUE TITLE
Fault result

### ISSUE THREAD

**Issue by pohmelie** [h2non/riprova#4]
Don't really know does it fits into your library (I mean, you decide what is relevant), but when I wrote my own «restarter» I use some `fault_result` argument, which returned as function result after attempts gone. In my case this was made to avoid try/except/pass things, cause function fault was like «Oh, fault! Ok, will call it later anyway, does not matter…». It looks like right now we can't do that without external try/except/pass wrapper.

**Comment by h2non** [comment]
Looks reasonable, but that behaviour should be explicitly defined by the user. I think I can easily support that, hopefully later today.

**Comment by h2non** [comment]
If I understood correctly you core idea here, you are basically suggesting about passing errors silently, is it? I don't think passing error silently is a cool idea from a library implementation perspective, but I could agree that in certain cases it might be DRYer. 

I'm open to introduce an exceptional capability that won't affect to predictability, and therefore the developer must be always aware of changing the default behavior.

From API perspective, what about explicitly passing an optional param to change raise behavior, and replace it:
```python
@riprova.retry(return_error=True)
```
Passing that param would imply that the typical raised error won't be raised, and instead it would be returned.

I think this approach is better since it's more explicit than and determines the behavior to activate, instead of the behavior to disable.

You can also pass any value in order to return a custom value on error:
```python
@riprova.retry(return_error=MyCustomError('oops!'))
```

My main question would be: should the `return_error` change the behavior for all the errors, legit or not, internally raised by `riprova` or raised by the retriable task?

I'm still feeling that this feature introduces a bit of unpredictability, which introduces FUD when using the library, and that's not something good IMO.

I'm open to suggestions.

**Comment by pohmelie** [comment]
> typical raised error won't be raised, and instead it would be returned.

If I need to inspect error, I will catch it with `except`. This api is useless from my point. Anyway, any `repeater` silently ignores errors, so I don't see nothing wrong with combination of attempts and fault result.

> should the `return_error` change the behavior for all the errors, legit or not, internally raised by `riprova` or raised by the retriable task?

Of course `asyncio.CancelledError` should not be masked. For asyncio, there is no other special cases. I think `KeyboardInterrupt` should not be masked too. Maybe something else…

**Comment by h2non** [comment]
I'm open to introduce this capability if you provide a solid implementation. 
Just send a PR is you are interested.

**Comment by pohmelie** [comment]
Ok, I will try to do it soon.

**Comment by pohmelie** [comment]
It become too complicated when I try to implement `fault_result`, since there is white/black lists and multiply points of error raising. Probably I don't have enough skill and motivation for this.

**Comment by h2non** [comment]
haha, fair enough.

**Comment by pohmelie** [comment]
More to say. There should be extra list of allowed exceptions for proper `fault_result` behavior, which user will pass to retrier. Probably this is a bad idea.

**Comment by h2non** [comment]
I was thinking that this logic could be easly integrated overloading `evaluator` function: if it returns a non `bool` or `Exception` object, then the returned value should be used and the retry cycle should be stopped.

Sounds suitable for your original idea?

**Comment by pohmelie** [comment]
There is a chance, that I want return bool as `fault_result` :smile:
So this will not work.

**Comment by h2non** [comment]
You could wrap the return value with a custom type, such as `RiprovaResult(value)`. That would remove any ambiguity
